# Generated by Django 4.2.1 on 2023-05-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='book',
            field=models.FileField(default=1, upload_to='pdfs/'),
            preserve_default=False,
        ),
    ]
