# Generated by Django 4.2.1 on 2023-05-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_file_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='book',
            field=models.FileField(upload_to='media/uploaded/'),
        ),
    ]
